### ISSUE TITLE
Displacement of the Axis in the OTF Plot

### ISSUE THREAD

**Issue by jonas-funk** [eguomin/regDeconProject#1]
In Line 242 of BackProjector.m shouldn't it be:

    plot(0:Sox-1,line1/max(line1(1)),0:Sox-1,line2/max(line2(1)),'LineWidth',2);

to start at 0, so the values of the OTFs are correctly aligned ?  (Best seen at the resolution limit)

Regards
Jonas Funk

**Comment by eguomin** [comment]
Thanks for pointing out this, Jonas. The code has been updated based on your suggestion.
