### ISSUE TITLE
It looks like that”BlendZ“ was not defined in 'BigData_Postprocessing'

### ISSUE THREAD

**Issue by ZhenhongDu** [eguomin/regDeconProject#2]
Hello,
  Sorry to disturb you, I found that ”BlendZ“ was not defined in 'BigData_Postprocessing' in line 542
https://github.com/eguomin/regDeconProject/blob/a59a0c5cca122daba8e296564f3bc8d6b4ec26cd/ClearedTissueProcessing/BigData_Postprocessing.m#L542

  When I run the program, it returns:
```
Unrecognized function or variable 'BlendZ'.

Error in stitch_test>StitchingZ (line 56)
     OverlapZ = BlendZ(overlap_bottom, overlap_top,ramp_start,overlap);

Error in stitch_test (line 12)
StitchingZ(file_path_in, file_path_out, CropStepXY, CropStepZ, tilex, tiley, tilez);
```

'sitch_test' is my self-define code 

Can i ask you for help ! thanks

**Comment by eguomin** [comment]
Thanks, we have uploaded the [BlendZ](https://github.com/eguomin/regDeconProject/blob/master/ClearedTissueProcessing/BlendZ.m) function.

**Comment by ZhenhongDu** [comment]
Thanks !
